### ISSUE TITLE
vasm: Rust panic when using \n as a character literal

### ISSUE THREAD

**Issue by starscouts** [floofi-org/vixen#15]
### Expected behavior
The line `mov {TTY_STDOUT}, #'\n'` gets preprocessed as `mov $04000200, #$10`.

### Actual behavior
The following Rust panic shows up:

```
thread 'main' panicked at assembler/src/scanner/token.rs:50:22:
Unterminated char literal
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_display
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:264:5
   3: core::option::expect_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/option.rs:2021:5
   4: core::option::Option<T>::expect
             at /shelter/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:933:21
   5: vasm::scanner::token::<impl vasm::models::token::span::TokenWithSpan>::scan
             at ./assembler/src/scanner/token.rs:48:17
   6: vasm::scanner::Scanner::scan
             at ./assembler/src/scanner.rs:30:31
   7: vasm::assemble
             at ./assembler/src/lib.rs:14:18
   8: vasm::run_assembler
             at ./assembler/src/main.rs:18:19
   9: vasm::main
             at ./assembler/src/main.rs:27:21
  10: core::ops::function::FnOnce::call_once
             at /shelter/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Steps to reproduce
1. Write an assembly program with `#'\n'` in it
2. Try to compile it

### System configuration
See #14.

**Comment by starscouts** [comment]
Fixed in 24de909
